# Generated by Django 5.0.1 on 2024-01-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_alter_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=models.CharField(choices=[('FE', 'Front-end'), ('BE', 'Back-end')], default='D', max_length=2),
        ),
    ]
